modules:
  authenticator:
    namespace: "App\\Authenticator"
    routers:
      basic:
        pattern: "\\/authenticators(\\/.*)?"
        prefix: "\\/"
        namespace: "App\\Authenticator\\Controller"

application:
  services:
    authenticatorManager:
      className: "App\\Authenticator\\Service\\AuthenticatorManager"
      services:
        config:
          di: "config"
        userAuthenticatorsRepository:
          di: "userAuthenticatorsRepository"
        usersRepository:
          di: "usersRepository"

  repositories:
    authenticatorsRepository: "App\\Authenticator\\Repository\\AuthenticatorsRepository"
    userAuthenticatorsRepository: "App\\Authenticator\\Repository\\UserAuthenticatorsRepository"
